# AWS 
aws_profile: default
aws_region: us-east-2 # must match your aws config profile - used for community.aws modules
# aws_linux_ami: ami-096fda3c22c1c990a # must be for your region
# aws_windows_ami: ami-029bfac3973c1bda1 # must be for your region
aws_instance_type: t2.medium 
username: ec2-user
ansible_user: ec2-user 

# Key pair 
public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  
private_key: "{{ lookup('file', '~/.ssh/id_rsa') }}"  

# Demo specific items 
servicenow_git_branch: platform 
windows_git_branch: platform

# DNS Information needed for certificate request
controller_dns: controller.{{ top_level_domain }}
sso_dns: sso.{{ top_level_domain }}
catalog_dns: catalog.{{ top_level_domain }}

# For dealing with certificates 
controller_cert_dest: /etc/security/tower.cert
controller_key_dest: /etc/security/tower.key
java_keystore_dest: /etc/security/sso.jks