---
collections:
  - name: community.aws
    version: 5.0.0 
  - ansible.windows
  # - community.windows
  - name: amazon.aws
    version: 3.0.0
  - name: ansible.controller
    version: 4.1.0 
  - containers.podman
  # - ansible.tower
  - community.general