---
collections:
  - name: community.aws
    version: 1.5.0 
  - ansible.windows
  # - community.windows
  - name: amazon.aws
    version: 3.0.0
  - awx.awx
  - containers.podman
  # - ansible.tower
  - community.general