---
- name: Add user from JSON spec list 
  hosts: all 
  vars:
    users: "{{ survey_users.split('\n') }}"
    keys:
      - userid 
      - username 
      - newgroup 
      - expire 
      - pass
      - passreset    
  tasks:
    - name: create user list 
      set_fact:
        user_list: "{{ keys | zip(item.split(',')) | list }}"
      loop: "{{ users }}"
    - name: create user dict 
      set_fact:
        user_dict: "{{ user_dict | default({}) | combine({item[0]: item[1]}) }}"
    - name: print it 
      debug:
        var: user_dict
