---
- name: Add user from JSON spec list 
  hosts: all 
  vars:
    users: "{{ survey_users.split('\n') }}" 
  tasks:
    - name: Print user list 
      debug:
        msg: "{{ item.userid }}"
      loop: "{{ users }}"