---
- name: Add user from JSON spec list 
  hosts: all 
  vars:
    users: "{{ survey_users.split('\n') | from_json }}" 
  tasks:
    - name: Print user list 
      debug:
        var: users[0].userid