---
- name: Add user from JSON spec list 
  hosts: all 
  vars:
    users: "{{ survey_users.split('\n') }}"
    keys:
      - userid 
      - username 
      - newgroup 
      - expire 
      - pass
      - passreset    
  tasks:
    - name: Print user list 
      debug:
        msg: "{{ keys | zip(item.split(',')) | list }}"
      loop: "{{ users }}"