---
- name: Setup Controller infrastructure 
  hosts: localhost
  connection: local 
  gather_facts: no
  vars:
    group_name: "controller"
    short_desc: "controller"
    server_env: "test" 
    server_os: "linux"
    business_domain_name: "Red Hat"
    aws_instance_type: m4.xlarge
  # vars_prompt:
  #   - name: prompt_admin_password
  #     prompt: Set your initial Tower admin password
  #     private: yes
  #   - name: prompt_admin_password_confirm
  #     prompt: Confirm your initial Tower admin password
  #     private: yes
      
  tasks:
  - name: Check if tower admin passwords match
    fail:
      msg: Admin passwords do not match, please rerun setup.sh and reenter initial password 
    when: prompt_admin_password != prompt_admin_password_confirm

  - name: Find AWS User information
    amazon.aws.aws_caller_info:
      profile: "{{ aws_profile }}"
    register: user

  - name: Setup AWS
    include_role:
      name: aws-infra-setup 
    vars:
      aws_user: "{{ user.user_id | regex_search(':(.*)', '\\1') | join('') }}"
      
  - name: Get AWS infra info 
    include_role:
      name: aws-infra-info
    vars:
      aws_user: "{{ user.user_id | regex_search(':(.*)', '\\1') | join('') }}"
    
  - name: call provision role to create a RHEL 8 server to install Tower on 
    include_role:
      name: aws-ec2-provision 
    vars: 
      aws_user: "{{ user.user_id | regex_search(':(.*)', '\\1') | join('') }}"

  - name: Add the host 
    add_host:
      name: "{{ ec2.instances[0].public_ip_address }}"
      groups:
        - tower 
      ansible_ssh_private_key_file: ~/.ssh/id_rsa 
      ansible_user: ec2-user
      admin_password: "{{ prompt_admin_password }}"
      tower_ip: "{{ ec2.instances[0].public_ip_address }}"

- name: Install tower 
  hosts: tower 
  become: yes

  tasks:
    - name: Run updates 
      package:
        name: '*'
        state: latest 
        
    - name: Setup tower on AWS Instance 
      include_role:
        name: controller-setup

    - name: Add credentials
      include_role:
        name: controller-credentials

    - name: Add Inventories 
      include_role:
        name: controller-inventory 

    - name: Add Projects 
      include_role:
        name: controller-projects 
        
