---
- name: Pick a demo to stage 
  hosts: localhost 
  connection: local 
  tasks:
    - name: Setup Windows demo  
      debug:
        msg: "Hello World, you chose to demo {{ demo_name }}"
      when: demo_name == 'Windows'

    - name: Setup Linux demo  
      debug:
        msg: "Hello World, you chose to demo {{ demo_name }}"
      when: demo_name == 'Linux'

    - name: Setup ServiceNow demo  
      debug:
        msg: "Hello World, you chose to demo {{ demo_name }}"
      when: demo_name == 'ServiceNow'