---
- name: Pick a demo to stage 
  hosts: localhost 
  connection: local 
  tasks:

    - name: Setup Windows demo  
      include_role:
        name: windows
      when: demo_name == 'Windows'

    - name: Setup Linux demo  
      include_role:
        name: linux-patching
      when: demo_name == 'Linux'

    - name: Setup ServiceNow demo  
      include_role:
        name: servicenow
      when: demo_name == 'ServiceNow'