---
- name: Use crypto policies RHEL System Role 
  hosts: all 
  become: yes
  vars:
    crypto_policies_policy: "DEFAULT:NO-SHA1"
    crypto_policies_reload: false
  roles:
    - role: redhat.rhel_system_roles.crypto_policies