---
- name: Setup Tower infrastructure 
  hosts: localhost
  connection: local 
  gather_facts: no
  vars:
    short_desc: "{{ survey_short_desc }}"
    business_domain_name: "{{ survey_business_domain_name | default('Red Hat') }}"
  tasks:
    - name: Deprovision Instance
      include_role:
        name: aws-ec2-deprovision 

    - name: Update deprovision list 
      include_role:
        name: controller-setup 
        tasks_from: deprovision-survey-list.yml