---
- name: Setup Tower infrastructure 
  hosts: localhost
  connection: local 
  gather_facts: no
  vars:
    short_desc: "{{ survey_short_desc | default('!tower')}}"
    business_domain_name: "{{ survey_business_domain_name | default('Red Hat') }}"
  tasks:
    - name: Deprovision Instance
      include_role:
        name: aws-ec2-deprovision 