--- 
- name: setup HA proxy
  hosts: tag_loadbalancer 
  become: yes 
  vars: 
    haproxy_backend_servers:
      - name: app1
        address: "{{ hostvars[groups['tag_application']] }}"
      - name: app2
        address: "{{ hostvars[groups['tag_application']] }}"

  tasks:
    - name: print IP Address of app1 host
      debug:
        var: "{{ item }}"
      loop: "{{ haproxy_backend_servers }}"
  # roles:
  #   - geerlingguy.haproxy
