--- 
- name: Apache webserver setup.
  hosts: tag_application
  become: yes

  tasks:
    - name: latest Apache version installed
      package:
        name: httpd
        state: latest

    - name: Apache enabled and running
      service:
        name: httpd
        enabled: true
        state: started

    - name: Copy basic website to server 
      copy:
        src: shaded-relief.html
        dest: /var/www/html/index.html


- name: setup HA proxy
  hosts: tag_loadbalancer 
  become: yes 
  vars: 
    haproxy_backend_servers:
      - name: "{{ hostvars[groups['tag_application'][1]]['private_ip_address'] }}"
        address: "{{ hostvars[groups['tag_application'][1]]['private_ip_address'] }}:80"
      - name: "{{ hostvars[groups['tag_application'][1]]['private_ip_address'] }}"
        address: "{{ hostvars[groups['tag_application'][1]]['private_ip_address'] }}:80"

  roles:
    - geerlingguy.haproxy
