---
- name: Update packages
  hosts: all 
  become: yes 
  vars:
    packages: "{{ survey_list_packages }}"
  tasks:
    - name: Update packages 
      package:
        name: "{{ packages }}"
        state: latest