--- 
- name: setup HA proxy
  hosts: tag_loadbalancer 
  become: yes 
  vars: 
    haproxy_backend_servers:
      - name: app1
        address: "{{ hostvars[groups['tag_application'][1]]['private_ip_address'] }}"
      - name: app2
        address: "{{ hostvars[groups['tag_application'][1]]['private_ip_address'] }}"

  tasks:
    - name: Print group tag thing
      debug:
        var: haproxy_backend_servers

    # - name: print IP Address of app1 host
    #   debug:
    #     var: "{{ item }}"
    #   loop: "{{ haproxy_backend_servers }}"

  # roles:
  #   - geerlingguy.haproxy
