---
- name: Setup Tower infrastructure 
  hosts: localhost
  connection: local 
  gather_facts: no
  vars:
    group_name: "{{ survey_group_name }}"
    short_desc: "{{ survey_short_desc }}"
    server_env: "{{ survey_server_env }}" 
    server_os: "{{ survey_server_os }}"
    business_domain_name: "{{ survey_business_domain_name | default('Red Hat') }}"
  tasks:
    - name: Find AWS User information
      amazon.aws.aws_caller_info:
        profile: "{{ aws_profile | default('') }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: user

    - name: Get AWS Infra info 
      include_role:
        name: aws-infra-info 
      vars:
        aws_user: "{{ user.user_id | regex_search(':(.*)', '\\1') | join('') }}"

    - name: Provision Instance
      include_role:
        name: aws-ec2-provision 
      vars: 
        aws_user: "{{ user.user_id | regex_search(':(.*)', '\\1') | join('') }}"

    - name: Update deprovision list 
      include_role:
        name: controller-setup 
        tasks_from: deprovision-survey-list.yml

    - name: Update AWS Inventory 
      ansible.controller.inventory_source_update:
        name: AWS  
        inventory: AWS
        wait: True
        tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
        tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
        tower_verify_ssl: "{{ override_verify_ssl | default(true) }}"