---
- name: Setup Tower infrastructure 
  hosts: localhost
  connection: local 
  gather_facts: no
  vars:
    group_name: "tower"
    short_desc: "tower"
    server_env: "test" 
    server_os: "linux"
    business_domain_name: "Red Hat"
    admin_password: "{{ prompt_admin_password }}"
  vars_prompt:
    - name: prompt_admin_password
      prompt: Enter your Ansible Tower admin password
      private: yes
  tasks:
  - name: Find AWS User information
    amazon.aws.aws_caller_info:
      profile: "{{ aws_profile }}"
    register: user

  - name: Update AWS Credential 
    vars:
      aws_user: "{{ user.user_id | regex_search(':(.*)', '\\1') | join('') }}"
    awx.awx.tower_credential:
      state: present
      name: AWS
      description: AWS Credential from saml 
      organization: Default 
      credential_type: Amazon Web Services
      inputs:
        username: "{{ lookup('ini', 'aws_access_key_id section=saml file=~/.aws/credentials') }}"
        password: "{{ lookup('ini', 'aws_secret_access_key section=saml file=~/.aws/credentials') }}"
        security_token: "{{ lookup('ini', 'aws_security_token section=saml file=~/.aws/credentials') }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ admin_password }}"
      tower_host: "https://ansible.{{ aws_user }}.ade.redhatgov.io"
      tower_verify_ssl: true