---
  - name: Apache server installed
    hosts: all
    become: true
    vars:
      survey_service: ""  
      survey_state: started 
    tasks:
    - name: Apache enabled and running
      service:
        name: "{{ survey_service }}"
        enabled: true
        state: "{{ survey_state }}"