--- 
- name: setup HA proxy
  hosts: tag_loadbalancer 
  become: yes 
  vars: 
    haproxy_backend_servers:
      - name: app1
        address: "{{ hostvars[groups['tag_application'][0]]['ansible_eth0']['ipv4']['address'] }}"
      - name: app2
        address: "{{ hostvars[groups['tag_application'][1]]['ansible_eth0']['ipv4']['address'] }}"

  tasks:
    - name: print IP Address of app1 host
      debug:
        var: "{{ haproxy_backend_servers }}"
  # roles:
  #   - geerlingguy.haproxy
