---
- name: Start AAP Instances
  hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
  - name: Find AAP EC2 Instances 
    amazon.aws.ec2_instance_info:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      filters:
        tag:server_env: "test" 
        tag:business_domain_name: "Red Hat"
        instance-state-name: stopped
    register: instances

  - name: Start AAP EC2 Instance
    amazon.aws.ec2_instance:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      instance_ids:
        - "{{ item.instance_id }}"
      wait: yes
      state: running 
    loop: instance.instances

  - name: Find Controller EC2 Instance Public IP Address
    amazon.aws.ec2_instance_info:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      filters:
        tag:group_name: "controller"
        tag:short_desc: "controller"
        tag:server_env: "test" 
        tag:server_os: "linux"
        tag:business_domain_name: "Red Hat"
        instance-state-name: running
    register: ec2

  - name: Setup Route 53 for domain name 
    community.aws.route53:
      profile: "{{ aws_profile }}"
      state: present 
      zone: "{{ top_level_domain }}"
      record: "ansible.{{ top_level_domain }}"
      type: A
      ttl: 300
      value: "{{ ec2.instances[0].public_ip_address }}"
      wait: yes
      overwrite: yes
    become: no
    delegate_to: localhost
      
  - name: Message 
    debug:
      msg: 
        - "It will take around 5 minutes for the Route 53 domain to update before you can access tower"
        - "Access Tower here: https://ansible.{{ top_level_domain }}"