---
- name: Start Tower Instance
  hosts: localhost
  connection: local 
  gather_facts: no
  vars:
    group_name: "tower"
    short_desc: "tower"
    server_env: "test" 
    server_os: "linux"
    business_domain_name: "Red Hat"
  tasks:
  - name: Find AWS User information
    amazon.aws.aws_caller_info:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    register: user

  - name: Stop Tower EC2 Instance 
    amazon.aws.ec2:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      instance_tags:
        group_name: "tower"
        short_desc: "tower"
        server_env: "test" 
        server_os: "linux"
        business_domain_name: "Red Hat"
      state: running
    register: ec2

  - name: Setup Route 53 for domain name 
    community.aws.route53:
      profile: "{{ aws_profile }}"
      state: present 
      zone: redhatgov.io
      record: "ansible.{{ aws_user }}.ade.redhatgov.io"
      type: A
      value: "{{ ec2.instances[0].public_ip_address }}"
      wait: yes
      overwrite: yes
    become: no
    delegate_to: localhost
      
  - name: Message 
    debug:
      msg: "It will take around 5 minutes for the Route 53 domain to update before you can access tower"