---
- name: Stop AAP Instances
  hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
  - name: Stop AAP EC2 Instance 
    amazon.aws.ec2_instance:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      filters:
        tag:server_env: "test" 
        tag:business_domain_name: "Red Hat"
        instance-state-name: running
      state: stopped