---
- name: Stop Tower Instance
  hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
  - name: Stop Tower EC2 Instance 
    amazon.aws.ec2_instance:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      filters:
        tag:group_name: "controller"
        tag:short_desc: "controller"
        tag:server_env: "test" 
        tag:server_os: "linux"
        tag:business_domain_name: "Red Hat"
        instance-state-name: running
      state: stopped