---
- name: Setup Controller infrastructure 
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
    - name: setup credentials
      include_role:
        name: controller-credentials