---
- name: Use TimeSync RHEL System Role 
  hosts: all 
  become: yes
  vars:
    timesync_ntp_servers:
      - hostname: 2.rhel.pool.ntp.org
        pool: yes 
        iburst: yes 
  roles:
    - role: redhat.rhel_system_roles.timesync