--- 
- name: Deprovision ec2 instance 
  amazon.aws.ec2_instance:
    profile: "{{ aws_profile | default('') }}"
    state: absent
    filters:
      # "tag:business_domain_name": "{{ business_domain_name }}"
      "tag:short_desc": "{{ short_desc }}"
      "tag:demo": Ansible 
      instance-state-name: running 
    wait: yes
    region: "{{ aws_region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: deprovision