---
- name: Setup ServiceNow project 
  awx.awx.tower_project:
    name: ServiceNow 
    state: present
    wait: yes
    organization: Default 
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true
    scm_type: git 
    scm_branch: "{{ servicenow_git_branch }}"
    scm_url: https://github.com/corumj/ansible-servicenow-demo.git
    scm_update_on_launch: yes 

- name: Setup ServiceNow - Initialize job template
  awx.awx.tower_job_template:
    name: "ServiceNow - Initialize Demo"
    job_type: "run"
    inventory: AWS
    project: ServiceNow
    playbook: "initialize.yml"
    organization: Default 
    credentials: 
      - "Tower Credential"
      - "AWS"
    survey_enabled: yes 
    survey_spec: "{{ lookup('file', 'servicenow.json') }}"
    state: "present"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Create tower team
  tower_team:
    name: ServiceNow
    description: ServiceNow administrators
    organization: Default
    state: present
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Add ServiceNow user
  tower_user:
    username: servicenow
    password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    email: ServiceNow@example.local
    first_name: ServiceNow
    last_name: User
    state: present
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: promote ServiceNow team to ServiceNow project admin
  tower_role:
    team: ServiceNow
    project: ServiceNow
    role: project_admin
    state: present

- name: Add ServiceNow user to team 
  tower_role:
    user: servicenow 
    target_team: ServiceNow
    role: member 
    state: present

- name: Install required python package
  pip:
    name: pysnow 
    state: present 
    executable: /usr/bin/pip3.6
  become: yes