---
- name: Find AWS User information
  amazon.aws.aws_caller_info:
    profile: "{{ aws_profile | default('') }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: user

- name: Get list of instances for user as part of this demo 
  community.aws.ec2_instance_info:
    profile: "{{ aws_profile | default('') }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    filters:
      instance-state-name: running 
      tag:business_domain_name: Red Hat 
      tag:demo: Ansible 
      tag:user: "{{ user.user_id | regex_search(':(.*)', '\\1') | join('') }}"
  register: ec2 

- name: Create Deprovision Template
  vars:
    aws_instances_short_desc: "{{ ec2 | json_query('instances[*].tags.short_desc') | difference(['tower']) | join('\n') }}"
  awx.awx.tower_job_template:
    name: "3. Deprovision"
    job_type: "run"
    inventory: AWS
    project: Ansible Demo
    playbook: "deprovision.yml"
    credentials: 
      - "Tower Credential"
      - "AWS"
    survey_enabled: yes 
    survey_spec: "{{ lookup('template', 'deprovision.json.j2') }}"
    extra_vars:
      aws_profile: ''
    ask_variables_on_launch: yes
    state: "present"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true