# SSH Key defaults to your generic id_rsa.pub key so you don't have to use ssh agent to ssh to the infra servers
public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  
private_key: "{{ lookup('file', '~/.ssh/id_rsa') }}"  

## certificate related ssh keys/csr paths
acme_account_key_path: "{{ playbook_dir }}/generated_files/acme_key"
acme_private_key_path: "{{ playbook_dir }}/generated_files/cert_key"

controller_csr_path: "{{ playbook_dir }}/generated_files/{{ controller_dns }}"
sso_csr_path: "{{ playbook_dir }}/generated_files/{{ sso_dns }}"
catalog_csr_path: "{{ playbook_dir }}/generated_files/{{ catalog_dns }}"

