---
- name: Create tower organization for Windows
  awx.awx.tower_organization:
    name: Windows
    description: "Windows admins"
    state: present
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Create a credential for Galaxy in the Windows Org
  awx.awx.tower_credential:
    name: Windows Galaxy 
    description: Credential for Windows org to access Galaxy
    organization: Windows
    credential_type: Ansible Galaxy/Automation Hub API Token
    inputs:
      url: https://galaxy.ansible.com/
    state: present
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Setup Windows project 
  awx.awx.tower_project:
    name: Windows 
    state: present
    wait: yes
    organization: Windows 
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true
    scm_type: git 
    scm_branch: "{{ windows_git_branch }}"
    scm_url: https://github.com/corumj/ansible-windows-demo.git
    scm_update_on_launch: yes 

- name: Setup Windows - Initialize job template
  awx.awx.tower_job_template:
    name: "Windows - 1. Initialize Demo"
    job_type: "run"
    inventory: AWS
    project: Windows
    playbook: "initialize.yml"
    organization: Windows 
    credentials: 
      - "Tower Credential"
      - "AWS"
    survey_enabled: yes 
    survey_spec: "{{ lookup('file', 'windows.json') }}"
    state: "present"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Create tower team
  awx.awx.tower_team:
    name: ServiceNow
    description: ServiceNow administrators
    organization: ServiceNow
    state: present
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Add ServiceNow user
  awx.awx.tower_user:
    username: servicenow
    password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    email: ServiceNow@example.local
    first_name: ServiceNow
    last_name: User
    state: present
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: promote ServiceNow team to ServiceNow project admin
  awx.awx.tower_role:
    team: ServiceNow
    organization: ServiceNow
    role: project_admin
    state: present

- name: Add ServiceNow user to team 
  awx.awx.tower_role:
    user: servicenow 
    target_team: ServiceNow
    role: member 
    state: present

- name: Add team permissions to init playbook
  awx.awx.tower_role:
    team: ServiceNow
    job_template: SNOW- Initialize Demo
    role: admin 
    state: present

- name: Install required python package
  pip:
    name: pysnow 
    state: present